# Site settings
title: "Stephen Kerr"
description: "Computational materials scientist at Queen's University using atomistic simulation to study alloys and teach numerical methods."
author: "Stephen Kerr"
email: "24jrpc@queensu.ca"
linkedin: "https://linkedin.com/in/stephen-kerr-93aa42254/"

# Build settings
markdown: kramdown
theme: null

# GitHub Pages settings
baseurl: ""
url: ""

# Plugins
plugins:
  - jekyll-seo-tag

# Collections
collections:
  publications:
    output: false
  videos:
    output: false

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
