# Site settings
title: "Stephen Kerr"
description: "PhD candidate in computational materials science at Queen's University. Studying defect mechanisms in alloys using DFT and molecular dynamics."
author: "Stephen Kerr"
email: "24jrpc@queensu.ca"
linkedin: "https://linkedin.com/in/stephen-kerr-93aa42254/"

# Build settings
markdown: kramdown
theme: null

# GitHub Pages settings
baseurl: ""
url: ""

# Plugins
plugins:
  - jekyll-seo-tag

# Collections
collections:
  publications:
    output: false
  videos:
    output: false

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
